spring.datasource.url: jdbc:mysql://localhost:3306/phonebook
spring.datasource.username: root
spring.datasource.password: qwer12#$
spring.jpa.hibernate.ddl-auto: create

#spring.jpa.hibernate.ddl-auto: validate
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect